# Generated by Django 4.2.20 on 2025-04-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_phone_number_vendorprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
    ]
