# Generated by Django 4.2.20 on 2025-04-30 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('Thai', 'Thai'), ('Japanese', 'Japanese'), ('Indian', 'Indian'), ('Italian', 'Italian'), ('Local', 'Local')], max_length=50),
        ),
    ]
