# Generated by Django 4.2.20 on 2025-05-06 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_vendorprofile_photo_url_vendorprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('Thai', 'Thai'), ('Japanese', 'Japanese'), ('Indian', 'Indian'), ('Italian', 'Italian'), ('Local', 'Local'), ('Seafood', 'Seafood')], max_length=50),
        ),
    ]
