# Generated by Django 4.2.20 on 2025-04-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='category',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='location_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
