# Generated by Django 4.2.20 on 2025-05-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_photos/'),
        ),
    ]
